In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [3]:
dataset=pd.read_csv('Churn_Modelling.csv')

In [5]:
type(dataset)

pandas.core.frame.DataFrame

In [7]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [9]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          225     Spain  Female   41   
2          3    15619304      Onio          629    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [13]:
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13:14].values

In [15]:

x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [17]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


In [21]:
x.shape

(10000, 10)

In [23]:
ct=ColumnTransformer([('oh',OneHotEncoder(),[1,2])],remainder='passthrough')
x=ct.fit_transform(x)

In [25]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [27]:
x.shape

(10000, 13)

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
from sklearn.preprocessing import StandardScaler
sa=StandardScaler()


In [33]:
import joblib
joblib.dump(sa,"sc")

['sc']

In [35]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [37]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [39]:
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [41]:
model=Sequential()

In [43]:
x.shape

(10000, 13)

In [45]:
model.add(Dense(units=13,activation='relu',kernel_initializer='random_uniform'))# input layer

In [47]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [49]:
model.add(Dense(units=26,activation='relu',kernel_initializer='random_uniform'))

In [51]:
model.add(Dense(units=1,activation='sigmoid',kernel_initializer='random_uniform'))

In [53]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [55]:
x_train.shape

(8000, 13)

In [57]:
model.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 943us/step - accuracy: 0.7889 - loss: 0.5844
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8018 - loss: 0.4312
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7891 - loss: 0.4340
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - accuracy: 0.8143 - loss: 0.4126
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8254 - loss: 0.4135
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.8266 - loss: 0.4241
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8287 - loss: 0.4165
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8298 - loss: 0.4065
Epoch 9/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8288 - loss: 0.4137
Epoch 10/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.8343 - loss: 0.3941
Epoch 11/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.8270 - loss: 0.4081
Epoch 12/20
250/250 ━━━━━━━━━━━━━━

In [58]:
ypred=model.predict(x_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step


In [61]:
ypred

array([[0.22961375],
       [0.29809085],
       [0.15589894],
       ...,
       [0.23486573],
       [0.19762786],
       [0.16938496]], dtype=float32)

In [63]:
ypred=ypred>0.5
ypred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [65]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [67]:
dataset.head(1)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   

   Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       2      0.0              1          1               1        101348.88   

   Exited  
0       1

In [69]:
x.shape

(10000, 13)

In [71]:
x[0] = np.array(x[0].astype(np.float32))

In [73]:
x[0].dtype

dtype('O')

In [75]:
x[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 619.0, 42.0, 2.0, 0.0, 1.0, 1.0, 1.0,
       101348.8828125], dtype=object)

In [77]:
y_p=model.predict(x[0])

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

In [79]:
y_s=model.predict(np.array([[1.0, 0.0, 0.0, 1.0, 0.0, 619, 42, 2, 0.0, 1, 1, 1, 101348.88]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


In [81]:
y_s

array([[0.]], dtype=float32)

In [83]:
y_s

array([[0.]], dtype=float32)

In [85]:
p=np.array(sc.transform(ct.transform([[875,'France','Female',42,5,1234,0,1,1,1234567]])))

In [87]:
p

array([[ 1.04501206, -0.61433742, -0.57427105,  1.11339196, -1.11339196,
         2.35839422,  0.26349271, -0.04867536, -1.24761801, -2.54811601,
         0.66011376,  0.97628121, 19.77099386]])

In [89]:
yp=model.predict(p)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [91]:
yp

array([[0.01527482]], dtype=float32)

In [93]:
yp=yp>0.5
yp

array([[False]])