In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
# creating an array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
# checking  one dimension of array
a.ndim

1

In [9]:
# create 2 dimension array
b=np.array([[1,2,3,4,5],[2,3,4,5,6]])
b

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [10]:
b.ndim

2

In [17]:
# create 3 dimension array
c=np.array([[[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]]])
c

array([[[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]]])

In [18]:
c.ndim

3

# Zeros and Ones

In [19]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
var1=np.ones(10)
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
var2=np.ones((3,4,5))
var2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [24]:
var3=np.zeros((3,4,5))
var3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [29]:
var4=np.zeros((2,3,4,5))
var4

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [28]:
var4.ndim

2

# Functions

In [30]:
var=np.array([20,40,30,50])
var

array([20, 40, 30, 50])

In [31]:
var.ndim

1

In [32]:
type(var)

numpy.ndarray

In [33]:
#argmax- index position with max value
var.argmax()

3

In [34]:
#argmin- index position with lowest value
var.argmin()

0

In [35]:
var.argsort()

array([0, 2, 1, 3], dtype=int64)

In [36]:
var[1]

40

In [37]:
var[2]

30

In [38]:
var[0]

20

In [39]:
var

array([20, 40, 30, 50])

In [40]:
var[0:2]

array([20, 40])

In [41]:
var[1:3]

array([40, 30])

In [42]:
var[:-1]

array([20, 40, 30])

In [43]:
arr=np.array([1,2.4,3,4,5.2,6])
arr

array([1. , 2.4, 3. , 4. , 5.2, 6. ])

In [44]:
arr.dtype

dtype('float64')

In [45]:
arr.size

6

In [46]:
#arange()
np.arange(15) # end 
np.arange(0,15) # start and end
np.arange(0,11,3) # start, end and step

array([0, 3, 6, 9])

In [47]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [50]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a.ndim

1

In [52]:
#Reshape
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
a.size

12

In [ ]:
# To reshape into a matrix the new matrix should accomdate all the values of current array

In [55]:
a=np.arange(12).reshape(4,3)
a                                       #1,12,   2,6   3,4   4,3   6,2  12,1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
a=np.arange(12).reshape(3,4)
a  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a=np.arange(12).reshape(6,2)
a  

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [58]:
a.shape

(6, 2)

In [73]:
a=np.arange(12).reshape(1,6,2)
a 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [62]:
a.ndim

3

In [63]:
a.max()

11

In [64]:
a.min()

0

In [65]:
x=[1,4,5,2,8]
x

[1, 4, 5, 2, 8]

In [66]:
np.sqrt(x)

array([1.        , 2.        , 2.23606798, 1.41421356, 2.82842712])

In [81]:
np.log(x)

array([0.        , 1.38629436, 1.60943791, 0.69314718, 2.07944154])

In [68]:
np.exp(x)

array([2.71828183e+00, 5.45981500e+01, 1.48413159e+02, 7.38905610e+00,
       2.98095799e+03])

In [69]:
np.mean(x)

4.0

In [70]:
a


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [72]:
a1=a.T
a1

array([[[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]],

       [[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]])

# Floor and Ceil

In [82]:
arr1=np.array([10.8,3.64,6.12,10.2])
arr1

array([10.8 ,  3.64,  6.12, 10.2 ])

In [83]:
np.floor(arr1)

array([10.,  3.,  6., 10.])

In [84]:
np.ceil(arr1)

array([11.,  4.,  7., 11.])

In [87]:
np.floor(-3.47)

-4.0

In [88]:
round_data=np.round(arr1)
round_data

array([11.,  4.,  6., 10.])

# Stacking

In [89]:
arr1=np.arange(10).reshape(2,5)
arr2=np.arange(20).reshape(4,5)

In [90]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
# vertical Stacking- No of columns should be same
# horizontal stacking- No of rows should be same

In [93]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
np.hstack((arr1,arr2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [ ]:
# spliting
# vsplit- vertically
#hsplit- horizontally

In [95]:
arr2=np.arange(100).reshape(10,10)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
np.vsplit(arr2,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [97]:
np.hsplit(arr2,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [102]:
#linspace
np.linspace(0,30)

array([ 0.        ,  0.6122449 ,  1.2244898 ,  1.83673469,  2.44897959,
        3.06122449,  3.67346939,  4.28571429,  4.89795918,  5.51020408,
        6.12244898,  6.73469388,  7.34693878,  7.95918367,  8.57142857,
        9.18367347,  9.79591837, 10.40816327, 11.02040816, 11.63265306,
       12.24489796, 12.85714286, 13.46938776, 14.08163265, 14.69387755,
       15.30612245, 15.91836735, 16.53061224, 17.14285714, 17.75510204,
       18.36734694, 18.97959184, 19.59183673, 20.20408163, 20.81632653,
       21.42857143, 22.04081633, 22.65306122, 23.26530612, 23.87755102,
       24.48979592, 25.10204082, 25.71428571, 26.32653061, 26.93877551,
       27.55102041, 28.16326531, 28.7755102 , 29.3877551 , 30.        ])

In [ ]:
# random

In [110]:
np.random.rand(10)

array([0.62979522, 0.8356364 , 0.22152062, 0.84534163, 0.64163145,
       0.50232682, 0.18963134, 0.03987722, 0.43000214, 0.45435186])

In [109]:
# randint
np.random.randint(1,10)

9